### ISSUE TITLE
Doesn't work with Java 10

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-jacoco-agent#10]
Got feedback that nothing happens when Java 10 is used. Investigate potential problems

**Comment by karottenreibe** [comment]
Possibly: https://github.com/jacoco/jacoco/pull/629

**Comment by agoeb** [comment]
In that case it should work with any of our versions since at least v8.3.0, since they all use JaCoCo 0.8.1 already, which includes the pull request you linked.

**Comment by ilko-rbi** [comment]
Instrumentation for TGA enabled - configuring the agent...
Using TEAMSCALE_AGENT_OPTS: -javaagent:/metrics/lib/teamscale-jacoco-agent.jar=out=/metrics/out,class-dir=/service,interval=60,upload-metadata=/metrics/meta/version.json,includes=*....*,upload-url=<url>
Java HotSpot(TM) 64-Bit Server VM warning: Option MaxRAMFraction was deprecated in version 10.0 and will likely be removed in a future release.
Java HotSpot(TM) 64-Bit Server VM warning: Option UseCGroupMemoryLimitForHeap was deprecated in version 10.0 and will likely be removed in a future release.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/pattern/ThrowablePatternConverter
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at shadow.org.apache.logging.log4j.core.config.plugins.util.PluginRegistry.decodeCacheFiles(PluginRegistry.java:181)
        at shadow.org.apache.logging.log4j.core.config.plugins.util.PluginRegistry.loadFromMainClassLoader(PluginRegistry.java:119)
        at shadow.org.apache.logging.log4j.core.config.plugins.util.PluginManager.collectPlugins(PluginManager.java:132)
        at shadow.org.apache.logging.log4j.core.pattern.PatternParser.<init>(PatternParser.java:132)
        at shadow.org.apache.logging.log4j.core.pattern.PatternParser.<init>(PatternParser.java:113)
        at shadow.org.apache.logging.log4j.core.layout.PatternLayout.createPatternParser(PatternLayout.java:246)
        at shadow.org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:375)
        at shadow.org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:137)
        at shadow.org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
        at shadow.org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:652)
        at shadow.org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:580)
        at shadow.org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
        at shadow.org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:86)
        at shadow.org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
        at shadow.org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
        at shadow.org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
        at shadow.org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:169)
        at shadow.org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:86)
        at shadow.org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:67)
        at eu.cqse.teamscale.jacoco.util.LoggingUtils.initializeDefaultLogging(LoggingUtils.java:43)
        at eu.cqse.teamscale.jacoco.util.LoggingUtils.initializeLogging(LoggingUtils.java:52)
        at eu.cqse.teamscale.jacoco.agent.PreMain.premain(PreMain.java:23)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.pattern.ThrowablePatternConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 37 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by ilko-rbi** [comment]
the above is from the latest 9.0.2 - the class is there, some misconfiguration, maybe:

~/tools/jdk/bin/jar -tf teamscale-jacoco-agent.jar |grep ThrowablePatternConverter
shadow/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverter.class
shadow/org/apache/logging/log4j/core/pattern/ThrowablePatternConverter.class
shadow/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverter.class

**Comment by karottenreibe** [comment]
Possibly solved by #19. Ilko will check (I was unfortunately not able to reproduce the problem locally with a simple sample app so there might be some further complication with log4j somewhere?)

If the change from #19 fixes the problem (which I suspect since #19 gets rid of log4j entirely) we will prioritise merging #19 and then close this issue

**Comment by DreierF** [comment]
This is fixed now, right?

**Comment by karottenreibe** [comment]
correct!
