### ISSUE TITLE
WildFly fails to start with Agent

### ISSUE THREAD

**Issue by DreierF** [cqse/teamscale-jacoco-agent#100]
WildFly 17+ fails to start when upload to Teamscale is enabled with the following error:

```
INFO|12592/0|19-10-16 14:17:56|WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
INFO|12592/0|19-10-16 14:17:56|java.lang.reflect.InvocationTargetException
INFO|12592/0|19-10-16 14:17:56|         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|12592/0|19-10-16 14:17:56|         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|12592/0|19-10-16 14:17:56|         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|12592/0|19-10-16 14:17:56|         at java.lang.reflect.Method.invoke(Method.java:498)
INFO|12592/0|19-10-16 14:17:56|         at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|12592/0|19-10-16 14:17:56|         at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|12592/0|19-10-16 14:17:56|Caused by: java.lang.NoClassDefFoundError: org/jboss/logmanager/Level
INFO|12592/0|19-10-16 14:17:56|         at java.lang.Class.forName0(Native Method)
INFO|12592/0|19-10-16 14:17:56|         at java.lang.Class.forName(Class.java:348)
INFO|12592/0|19-10-16 14:17:56|         at org.jboss.modules.Module.run(Module.java:340)
INFO|12592/0|19-10-16 14:17:56|         at org.jboss.modules.Module.run(Module.java:320)
INFO|12592/0|19-10-16 14:17:56|         at org.jboss.modules.Main.main(Main.java:593)
INFO|12592/0|19-10-16 14:17:56|         ... 6 more
INFO|12592/0|19-10-16 14:17:56|Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Level
INFO|12592/0|19-10-16 14:17:56|         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
INFO|12592/0|19-10-16 14:17:56|         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO|12592/0|19-10-16 14:17:56|         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
INFO|12592/0|19-10-16 14:17:56|         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO|12592/0|19-10-16 14:17:56|         at org.jboss.modules.JDKSpecific.getSystemClass(JDKSpecific.java:180)
INFO|12592/0|19-10-16 14:17:56|         at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:395)
INFO|12592/0|19-10-16 14:17:56|         at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
INFO|12592/0|19-10-16 14:17:56|         ... 11 more
```

Workarounds similar to https://inspectit-performance.atlassian.net/wiki/spaces/DOC14/pages/5018025/JBoss+7.x did not fix the issue.

Turned out the issue is that Retrofit or OkHttp internally instantiate a logger which makes JBoss LogManager fail on startup.

**Comment by karottenreibe** [comment]
seems to be resolved
