### ISSUE TITLE
WebLogic Server Fails to Start Using Agent >= 8.3.0

### ISSUE THREAD

**Issue by agoeb** [cqse/teamscale-jacoco-agent#3]
Using a version >= 8.3.0, we encounter startup error in an environment running the WebLogic server.

```
   [java] weblogic.application.ModuleException: java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer not found
   [java]     at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
   [java]     at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
   [java]     at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:216)
   [java]     at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:211)
   [java]     at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
   [java]     Truncated. see log file for complete stacktrace
   [java] Caused By: java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer not found
   [java]     at java.util.ServiceLoader.fail(ServiceLoader.java:239)
   [java]     at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
   [java]     at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
   [java]     at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
   [java]     at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
   [java]     Truncated. see log file for complete stacktrace
```

With 8.2.0 the server successfully starts and profiles, so we suspect it is related to the JAXB references introduced with 8.3.0. Also, the shadowing introduced later does not fix the issue, i.e. the crash still appears in v9.0.0

**Comment by karottenreibe** [comment]
What java version are they using? Starting with I think Java 9 JAXB and some other Java EE stuff was removed from the JavaSE module and the JavaEE module needs to be loaded explicitly to be able to use JAXB. We should check if we really need JAXB in the agent since this makes configuring the agent a lot harder

**Comment by agoeb** [comment]
Asked about Java version. In case I can provide some more useful information, I'll be happy to help out. Currently I don't even know what to look for.

**Comment by agoeb** [comment]
Local Java Version

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b25)
Java HotSpot(TM) Client VM (build 25.171-b25, mixed mode)
```

Server Version:

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b25, mixed mode)
```

**Comment by DreierF** [comment]
@agoeb Any news on this one?

**Comment by agoeb** [comment]
Had no time to look into it on-site. Just asked them to test with v10.1.0.

**Comment by agoeb** [comment]
Does not happen anymore with 10.1.0
