### ISSUE TITLE
ClassFormatException when run in Tomcat

### ISSUE THREAD

**Issue by agoeb** [cqse/teamscale-jacoco-agent#31]
When attaching the agent to a Tomcat v7 (not tested with other versions yet), we get the following exception: 

`Nov 12, 2018 2:29:00 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SCHWERWIEGEND: Unable to process Jar entry [module-info.class] from Jar [jar:file:/Users/goeb/Downloads/teamscale-jacoco-agent/lib/teamscale-jacoco-agent.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:55)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:176)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:85)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2123)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1985)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1946)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1931)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5472)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Profiling seems to work nonetheless, but we should investigate the issue and try to resolve it anyway.

**Comment by agoeb** [comment]
https://stackoverflow.com/a/50568085 suggests that 19 is a Java 9 module descriptor, which is not supported in the BCEL version trying to understand the class. This would also explain the class name of `module-info.class`, in which it occurs. So I'm not sure whether we need to work around that. Maybe document?

**Comment by karottenreibe** [comment]
Migrated as TS-21142
