### ISSUE TITLE
NPE: getMainManifest() may return null

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-jacoco-agent#59]
Happened when we tried to read from a .war file at one customer. Can provide war file on demand.

**Comment by karottenreibe** [comment]
Stacktrace:


```
 Exception in thread "main" java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)

        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

Caused by: java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at com.teamscale.jacoco.agent.PreMain.premain(PreMain.java:33)

        ... 6 more

Caused by: java.lang.NullPointerException

        at com.teamscale.jacoco.agent.AgentOptionsParser.getCommitFromManifest(AgentOptionsParser.java:273)

        at com.teamscale.jacoco.agent.AgentOptionsParser.handleTeamscaleOptions(AgentOptionsParser.java:234)

        at com.teamscale.jacoco.agent.AgentOptionsParser.handleOption(AgentOptionsParser.java:109)

        at com.teamscale.jacoco.agent.AgentOptionsParser.readConfigFromFile(AgentOptionsParser.java:193)

        at com.teamscale.jacoco.agent.AgentOptionsParser.handleAgentOptions(AgentOptionsParser.java:129)

        at com.teamscale.jacoco.agent.AgentOptionsParser.handleOption(AgentOptionsParser.java:115)

        at com.teamscale.jacoco.agent.AgentOptionsParser.parse(AgentOptionsParser.java:79)

        at com.teamscale.jacoco.agent.AgentOptionsParser.parse(AgentOptionsParser.java:61)

        at com.teamscale.jacoco.agent.AgentBase.premain(AgentBase.java:42)

        ... 11 more 
```

**Comment by karottenreibe** [comment]
Is caused by a missing newline at the end of the Manifest

**Comment by agoeb** [comment]
Done and merged.
